### PR TITLE
Add required type hints

### PR DESCRIPTION
**Pull request by isosphere**
Library was failing to compile on rust 1.47.0, which prevented me from using stochastic. Tiny little type hints resolved the issue, as suggested by the compiler.

Test results:

```
running 6 tests
test forward_complex_small_m ... ok
test forward_real ... ok
test forward_complex_different_a ... ok
test forward_complex_large_m ... ok
test forward_complex ... ok
test forward_complex_different_w ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

### CODE REVIEW

**Comment by IvanUkhov** [comment]
Thank you for the pull request! I do not seem to be able to reproduce this error. I have tried with both stable and nightly (1.49.0) and did not observe any problems. Can you elaborate more on what you do and which versions you use?

**Comment by isosphere** [comment]
Here's the code I am using to interface with stochastic:

```
    let samples: usize = 10*2usize.pow(k.value_as::<u32>().unwrap()) + 1usize;
    let fbm = Motion::new(*holder);
    let mut source = source::default().seed([rng.gen::<u64>(), rng.gen::<u64>()]);
    let sampled_fbm = fbm.sample(samples, *fbm_magnitude, &mut source);
```
holder is a &f64

Not sure if that helps or not. 

stochastic = "0.5.2", allowed it to pull in whatever czt it wanted which appears to be czt = "0.3.6".

Here's the error without my change:

```
   Compiling czt v0.3.6 (C:\Users\Matt\Documents\Development\Rust\czt)
error[E0282]: type annotations needed for `num_complex::Complex<T>`
  --> C:\Users\Matt\Documents\Development\Rust\czt\src\transform.rs:23:19
   |
23 |         let one = Complex::one();
   |             ---   ^^^^^^^^^^^^ cannot infer type for type parameter `T` declared on the struct `Complex`
   |             |
   |             consider giving `one` the explicit type `num_complex::Complex<T>`, where the type parameter `T` is specified

error: aborting due to previous error

For more information about this error, try `rustc --explain E0282`.
error: could not compile `czt`.
```

I'm using rust on Windows 10 with stable-x86_64-pc-windows-msvc.

**Comment by IvanUkhov** [comment]
I’m on a mac. But take a look at what Travis says about GNU/Linux:

https://travis-ci.org/github/stainless-steel/czt

It indeed fails with 1.47.0. If you upgrade to  1.49.0, do you get the same?

**Comment by isosphere** [comment]
```
>rustc --version
rustc 1.49.0-nightly (b1af43bc6 2020-10-10)
```

```
 --> C:\Users\Matt\Documents\Development\Rust\czt\src\transform.rs:23:19
   |
23 |         let one = Complex::one();
   |             ---   ^^^^^^^^^^^^ cannot infer type for type parameter `T` declared on the struct `Complex`
   |             |
   |             consider giving `one` the explicit type `Complex<T>`, where the type parameter `T` is specified

error: aborting due to previous error

For more information about this error, try `rustc --explain E0282`.
error: could not compile `czt`
```

Seems to be the same on 1.49.0. My changes still work on nightly, and all tests still pass.

**Comment by IvanUkhov** [comment]
Thank you! Let’s merge.
